language: php

php:
  - 7.2

env:
  - BROWSER=chrome DB=pgsql TARGET_GROUP=front TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql TARGET_GROUP=admin01 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql TARGET_GROUP=admin02 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql TARGET_GROUP=admin03 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql92 TARGET_GROUP=front TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql92 TARGET_GROUP=admin01 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql92 TARGET_GROUP=admin02 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=pgsql92 TARGET_GROUP=admin03 TARGET_ENV=chrome,pgsql
  - BROWSER=chrome DB=mysql TARGET_GROUP=front TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql TARGET_GROUP=admin01 TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql TARGET_GROUP=admin02 TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql TARGET_GROUP=admin03 TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql55 TARGET_GROUP=front TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql55 TARGET_GROUP=admin01 TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql55 TARGET_GROUP=admin02 TARGET_ENV=chrome,mysql
  - BROWSER=chrome DB=mysql55 TARGET_GROUP=admin03 TARGET_ENV=chrome,mysql
  # - DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=front TARGET_ENV=chrome,pgsql
  # - DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin01 TARGET_ENV=chrome,pgsql
  # - DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin02 TARGET_ENV=chrome,pgsql
  # - DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin03 TARGET_ENV=chrome,pgsql

# matrix:
#   allow_failures:
#     - env: DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=front TARGET_ENV=chrome,pgsql
#     - env: DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin01 TARGET_ENV=chrome,pgsql
#     - env: DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin02 TARGET_ENV=chrome,pgsql
#     - env: DIRTYPE=subdir BROWSER=chrome DB=pgsql TARGET_GROUP=admin03 TARGET_ENV=chrome,pgsql

before_install:
  - docker-compose -f docker-compose.yml ${DIRTYPE:+-f docker-compose.${DIRTYPE}.yml} -f docker-compose.${BROWSER}.yml -f docker-compose.${DB}.yml --project-name ${BROWSER}_${DB}_${TARGET_GROUP} build --no-cache
  - mkdir -p tests/_support/_downloads
  - sudo chown -R 1000:1000 tests/_support/_downloads
script:
  - docker-compose -f docker-compose.yml ${DIRTYPE:+-f docker-compose.${DIRTYPE}.yml} -f docker-compose.${BROWSER}.yml -f docker-compose.${DB}.yml --project-name ${BROWSER}_${DB}_${TARGET_GROUP} run --rm codecept run -d ${USE_PLUGIN:+-g plugin_installer -g plugin_uninstaller} -g ${TARGET_GROUP} --env travis,${TARGET_ENV}

jobs:
  fast_finish: true
  include:
  - &e2e_test
    stage: E2E Test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_remove_store
    before_install: docker-compose -f docker-compose.yml -f docker-compose.${BROWSER}.yml -f docker-compose.${DB}.yml build --no-cache
    script: docker-compose -f docker-compose.yml -f docker-compose.${BROWSER}.yml -f docker-compose.${DB}.yml run -e NO_FIXTURES=1 --rm codecept run -d acceptance --env ${TARGET_ENV} EA10PluginCest:${TEST_TARGET}
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_update_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_update_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_update_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_disable_update_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_update_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_update_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_update_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_update_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_enable_enable
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_disable_disable
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_assets_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_assets_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_disabled_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_disabled_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_crossed_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_extend_same_table_crossed_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_dependency_each_install_plugin
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_dependency_plugin_install
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_dependency_plugin_update
  - <<: *e2e_test
    env: BROWSER=chrome DB=pgsql TARGET_ENV=chrome,pgsql TYPE=E2E TEST_TARGET=test_install_error
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_update_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_update_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_update_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_disable_update_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_update_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_update_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_update_enable_disable_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_update_enable_disable_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_enable_enable
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_disable_disable
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_assets_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_install_assets_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_disabled_remove_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_disabled_remove_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_crossed_store
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_extend_same_table_crossed_local
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_dependency_each_install_plugin
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=test_dependency_plugin_install
  - <<: *e2e_test
    env: BROWSER=chrome DB=mysql TARGET_ENV=chrome,mysql TYPE=E2E TEST_TARGET=install_enable_disable_enable_disable_remove_store
