version: "2"
services:
  db:
    image: eccube/postgres
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=cube3_dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cube3_dev
    network_mode: "host"
  eccube3:
    build:
      context: eccube3
      args:
        - ECCUBE_BRANCH=${ECCUBE_BRANCH}
        - ECCUBE_REPOS=${ECCUBE_REPOS}
        - DBTYPE=pgsql
    environment:
      - TZ=Asia/Tokyo
      - PGPASSWORD=password
      - POSTGRES_ENV_POSTGRES_PASSWORD=password
      - DBSERVER=localhost
    ports:
      - 80
      - 443
    depends_on:
      - db
      - mailcatcher
    restart: unless-stopped
    network_mode: "host"
  codecept:
    build:
      context: codeception
      args:
        - ECCUBE_BRANCH=${ECCUBE_BRANCH}
        - ECCUBE_REPOS=${ECCUBE_REPOS}
        - DBTYPE=pgsql
    depends_on:
      - browser
      - eccube3
    environment:
      - TZ=Asia/Tokyo
      - DBSERVER=localhost
      - SELENIUM_HOST=localhost
      - BASE_URL=http://localhost/
    volumes:
      - ./tests:/project/tests
      - ./codeception.yml:/project/codeception.yml
      - ./ff_profile.zip.b64:/root/ff_profile.zip.b64
      - ./tests/_support/_downloads:/project/downloads
    network_mode: "host"
  browser:
    image: selenium/standalone-firefox-debug:2.53.1
    ports:
      - 5900
    dns: 8.8.4.4
    environment:
      - TZ=Asia/Tokyo
      - no_proxy=localhost
    volumes:
      - ./tests/_support/_downloads:/home/seluser/Downloads
    network_mode: "host"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080
      - 1025
    environment:
      - TZ=Asia/Tokyo
    network_mode: "host"