version: "2"
services:
  eccube3:
    extends:
      file: docker-compose.common.yml
      service: eccube3
    image: ${DOCKER_USERNAME}/travis_ci_build_eccube3
    depends_on:
      - db
      - mailcatcher
  codecept:
    extends:
      file: docker-compose.common.yml
      service: codecept
    image: ${DOCKER_USERNAME}/travis_ci_build_codecept
    depends_on:
      - browser
      - eccube3
  mailcatcher:
    extends:
      file: docker-compose.yml
      service: mailcatcher
